# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\opencv_with_python\core\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.currTimeLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currTimeLabel.setFont(font)
        self.currTimeLabel.setObjectName("currTimeLabel")
        self.gridLayout.addWidget(self.currTimeLabel, 0, 0, 1, 1)
        self.showBinaryButton = QtWidgets.QPushButton(self.centralwidget)
        self.showBinaryButton.setObjectName("showBinaryButton")
        self.gridLayout.addWidget(self.showBinaryButton, 0, 4, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setAutoDefault(False)
        self.startButton.setDefault(False)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(24, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.currDateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currDateLabel.setFont(font)
        self.currDateLabel.setObjectName("currDateLabel")
        self.gridLayout.addWidget(self.currDateLabel, 0, 7, 1, 1)
        self.cameraNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.cameraNumber.setObjectName("cameraNumber")
        self.gridLayout.addWidget(self.cameraNumber, 0, 2, 1, 1)
        self.saveImage = QtWidgets.QPushButton(self.centralwidget)
        self.saveImage.setObjectName("saveImage")
        self.gridLayout.addWidget(self.saveImage, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.VidFrame = QtWidgets.QWidget(self.centralwidget)
        self.VidFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VidFrame.sizePolicy().hasHeightForWidth())
        self.VidFrame.setSizePolicy(sizePolicy)
        self.VidFrame.setMinimumSize(QtCore.QSize(640, 360))
        self.VidFrame.setMaximumSize(QtCore.QSize(1280, 720))
        self.VidFrame.setObjectName("VidFrame")
        self.gridLayout_2.addWidget(self.VidFrame, 1, 0, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setObjectName("generate")
        self.horizontalLayout_9.addWidget(self.generate)
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setObjectName("load")
        self.horizontalLayout_9.addWidget(self.load)
        self.output = QtWidgets.QPushButton(self.centralwidget)
        self.output.setObjectName("output")
        self.horizontalLayout_9.addWidget(self.output)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gp1x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp1x.setDecimals(4)
        self.gp1x.setMinimum(-10000.0)
        self.gp1x.setMaximum(10000.0)
        self.gp1x.setSingleStep(0.0)
        self.gp1x.setObjectName("gp1x")
        self.horizontalLayout.addWidget(self.gp1x)
        self.gp1y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp1y.setDecimals(4)
        self.gp1y.setMinimum(-10000.0)
        self.gp1y.setMaximum(10000.0)
        self.gp1y.setObjectName("gp1y")
        self.horizontalLayout.addWidget(self.gp1y)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gp2x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp2x.setDecimals(4)
        self.gp2x.setMinimum(-10000.0)
        self.gp2x.setMaximum(10000.0)
        self.gp2x.setObjectName("gp2x")
        self.horizontalLayout_2.addWidget(self.gp2x)
        self.gp2y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp2y.setDecimals(4)
        self.gp2y.setMinimum(-10000.0)
        self.gp2y.setMaximum(10000.0)
        self.gp2y.setObjectName("gp2y")
        self.horizontalLayout_2.addWidget(self.gp2y)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gp3x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp3x.setDecimals(4)
        self.gp3x.setMinimum(-10000.0)
        self.gp3x.setMaximum(10000.0)
        self.gp3x.setObjectName("gp3x")
        self.horizontalLayout_3.addWidget(self.gp3x)
        self.gp3y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp3y.setDecimals(4)
        self.gp3y.setMinimum(-10000.0)
        self.gp3y.setMaximum(10000.0)
        self.gp3y.setObjectName("gp3y")
        self.horizontalLayout_3.addWidget(self.gp3y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.gp4x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp4x.setDecimals(4)
        self.gp4x.setMinimum(-10000.0)
        self.gp4x.setMaximum(10000.0)
        self.gp4x.setObjectName("gp4x")
        self.horizontalLayout_4.addWidget(self.gp4x)
        self.gp4y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gp4y.setDecimals(4)
        self.gp4y.setMinimum(-10000.0)
        self.gp4y.setMaximum(10000.0)
        self.gp4y.setObjectName("gp4y")
        self.horizontalLayout_4.addWidget(self.gp4y)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pp1x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp1x.setDecimals(4)
        self.pp1x.setMinimum(-10000.0)
        self.pp1x.setMaximum(10000.0)
        self.pp1x.setObjectName("pp1x")
        self.horizontalLayout_5.addWidget(self.pp1x)
        self.pp1y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp1y.setDecimals(4)
        self.pp1y.setMinimum(-10000.0)
        self.pp1y.setMaximum(10000.0)
        self.pp1y.setObjectName("pp1y")
        self.horizontalLayout_5.addWidget(self.pp1y)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.pp2x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp2x.setDecimals(4)
        self.pp2x.setMinimum(-10000.0)
        self.pp2x.setMaximum(10000.0)
        self.pp2x.setObjectName("pp2x")
        self.horizontalLayout_6.addWidget(self.pp2x)
        self.pp2y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp2y.setDecimals(4)
        self.pp2y.setMinimum(-10000.0)
        self.pp2y.setMaximum(10000.0)
        self.pp2y.setObjectName("pp2y")
        self.horizontalLayout_6.addWidget(self.pp2y)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.pp3x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp3x.setDecimals(4)
        self.pp3x.setMinimum(-10000.0)
        self.pp3x.setMaximum(10000.0)
        self.pp3x.setObjectName("pp3x")
        self.horizontalLayout_7.addWidget(self.pp3x)
        self.pp3y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp3y.setDecimals(4)
        self.pp3y.setMinimum(-10000.0)
        self.pp3y.setMaximum(10000.0)
        self.pp3y.setObjectName("pp3y")
        self.horizontalLayout_7.addWidget(self.pp3y)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.pp4x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp4x.setDecimals(4)
        self.pp4x.setMinimum(-10000.0)
        self.pp4x.setMaximum(10000.0)
        self.pp4x.setObjectName("pp4x")
        self.horizontalLayout_8.addWidget(self.pp4x)
        self.pp4y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pp4y.setDecimals(4)
        self.pp4y.setMinimum(-10000.0)
        self.pp4y.setMaximum(10000.0)
        self.pp4y.setObjectName("pp4y")
        self.horizontalLayout_8.addWidget(self.pp4y)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.inputpixelX = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputpixelX.setDecimals(4)
        self.inputpixelX.setMinimum(-10000.0)
        self.inputpixelX.setMaximum(10000.0)
        self.inputpixelX.setObjectName("inputpixelX")
        self.horizontalLayout_10.addWidget(self.inputpixelX)
        self.inputpixelY = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputpixelY.setDecimals(4)
        self.inputpixelY.setMinimum(-10000.0)
        self.inputpixelY.setMaximum(10000.0)
        self.inputpixelY.setObjectName("inputpixelY")
        self.horizontalLayout_10.addWidget(self.inputpixelY)
        self.getpixel = QtWidgets.QPushButton(self.centralwidget)
        self.getpixel.setObjectName("getpixel")
        self.horizontalLayout_10.addWidget(self.getpixel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 21))
        self.menubar.setObjectName("menubar")
        self.menuCalibation = QtWidgets.QMenu(self.menubar)
        self.menuCalibation.setObjectName("menuCalibation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncalibation = QtWidgets.QAction(MainWindow)
        self.actioncalibation.setObjectName("actioncalibation")
        self.menuCalibation.addAction(self.actioncalibation)
        self.menubar.addAction(self.menuCalibation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "opencv_pyqt5"))
        self.currTimeLabel.setText(_translate("MainWindow", "HH:MM:SS PM"))
        self.showBinaryButton.setText(_translate("MainWindow", "tracking"))
        self.startButton.setText(_translate("MainWindow", "Start Video"))
        self.currDateLabel.setText(_translate("MainWindow", "DD-MMM-YYYY"))
        self.saveImage.setText(_translate("MainWindow", "SaveImage"))
        self.generate.setText(_translate("MainWindow", "Generate"))
        self.load.setText(_translate("MainWindow", "Load"))
        self.output.setText(_translate("MainWindow", "output"))
        self.label_5.setText(_translate("MainWindow", "Global (X,Y)"))
        self.label.setText(_translate("MainWindow", "Point 1"))
        self.label_2.setText(_translate("MainWindow", "Point 2"))
        self.label_3.setText(_translate("MainWindow", "Point 3"))
        self.label_4.setText(_translate("MainWindow", "Point 4"))
        self.label_6.setText(_translate("MainWindow", "pixel (X,Y)"))
        self.label_7.setText(_translate("MainWindow", "Point 1"))
        self.label_8.setText(_translate("MainWindow", "Point 2"))
        self.label_9.setText(_translate("MainWindow", "Point 3"))
        self.label_10.setText(_translate("MainWindow", "Point 4"))
        self.label_11.setText(_translate("MainWindow", "input pixel"))
        self.getpixel.setText(_translate("MainWindow", "getpixel"))
        self.menuCalibation.setTitle(_translate("MainWindow", "Setting"))
        self.actioncalibation.setText(_translate("MainWindow", "calibation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

